### PR TITLE
jsdoc

### PR DESCRIPTION
**Pull request by JohnCoene**
This adds the jsdoc plugin and an example.

Note that it adds an example of documented function in `srcjs/index.js`.

```js
/**
 * Adds 1 to a number.
 * 
 * @param  {Number} x Number to add one to
 */
export const fn = (x) => {
  return x + 1;
} 
```

You can view the generated docs (only applies to exported functions) with `browseURL("jsdoc/index.html")`

You forgot to add the plugin.

### CODE REVIEW

**Comment by DivadNojnarg** [comment]
Hum actually it does not solve my issue with the "Add doc comments" vscode extension.

**Comment by JohnCoene** [comment]
Worked for me in your project for this PR

**Comment by DivadNojnarg** [comment]
Did you tried on a `<>.f7.jsx` script. I tried withing a `.js` script which works well but `<>.f7.jsx` does nothing.

**Comment by DivadNojnarg** [comment]
Let me show you ;) (first is js and second is jsx). 

https://user-images.githubusercontent.com/18291543/132195565-95a1cd44-95ca-4a80-a1e3-e75404b12670.mov

**Comment by DivadNojnarg** [comment]
What I think is that jsdoc supports JSX since (2015) but the extension Add doc comment does not (https://github.com/Microsoft/vscode-comment: archived since 6 years).

**Comment by JohnCoene** [comment]
Yes, indeed the extension is archived. Maybe there's a new one for that. Perhaps even built in vscode, I should check

**Pull request merged**
